"""update tables to latest

Revision ID: f5d7d3075bd4
Revises: 309563603f35
Create Date: 2024-05-19 16:06:05.282134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d7d3075bd4'
down_revision = '309563603f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name=op.f('fk_squads_owner_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads'))
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_posts_squad_id_squads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_table('squadusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership', sa.Boolean(), nullable=True),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squadusers_squad_id_squads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_squadusers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squadusers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squadusers')
    op.drop_table('posts')
    op.drop_table('squads')
    op.drop_table('users')
    # ### end Alembic commands ###
